### ISSUE TITLE
Add dockerfile

### ISSUE THREAD

**Issue by bobrolov** [MihailBelyaev/RustTestProject#1]
Добавить докерфайл, который будет билдить рабочий образ с программой, основываясь на Rust образ из докер харбора:
Примерно следующие слои:
* взять докер образ раст
* сделать растап апдейт, чтобы обновить раст
* склонить этот репозиторий в папку ~/my_app
* сбилдить проект с флагом --release
* настроить переменные среды (порт, на котором работает рест, сетевой путь до  монги)
* настроить, чтобы при запуске образа сразу запускалась программа

**Comment by BogdanovAleksei** [comment]
Возможно лучше сделать мультистейдж сборку, так как собирать код и запускать релиз проект в одном образе - Это не очень хорошо! Если ты не имел ввиду сборку проекта на CI и упаковку в докер только бинаря
