### ISSUE TITLE
Добавить докер-компоуз файл

### ISSUE THREAD

**Issue by bobrolov** [MihailBelyaev/RustTestProject#3]
Нужно чтобы по программе docker-compose up поднимался образ программы, а так же запускался образ монги, и чтобы они находились в одной виртуальной сети

**Comment by BogdanovAleksei** [comment]
Но при этом монга была доступна только из приложения, а с хоста к ней доступа не было. То есть монга с приложением должна быть в отдельной виртуальной сети, а апи порт приложения должен смотреть наружу!
