### ISSUE TITLE
Добавить в рест запросы авторизацию

### ISSUE THREAD

**Issue by bobrolov** [MihailBelyaev/RustTestProject#4]
Нужно, чтобы при всех рест запросах добавились хидеры с логином паролем.
Пока что это можно захардкодить, например login: user, password: pass.
Если в запросе нет хидера, или логин пароль неправильный - отдавать ошибку 403 Forbidden

**Comment by BogdanovAleksei** [comment]
Лучше сделать отдельный ендпойнт `login` с базовой авторизацией, который возвращает токен для доступа к остальным ендпойнтам, пока можно захардкодить сам токен, и обрабатывать любые пары логин/пароль!

**Comment by MihailBelyaev** [comment]
Что понимается под токеном? Какой-то чудо-хэш, который я с серверным сравниваю при запросах?
