### ISSUE TITLE
Добавить в систему БД с логинами паролями

### ISSUE THREAD

**Issue by bobrolov** [MihailBelyaev/RustTestProject#5]
В проект нужно добавить sqlite, который работает через библиотеку Diesel с миграцией
В sqlite есть таблица - это список логинов паролей пользователей
И соответственно программа при авторизации ищет в sql по логину и паролю и если находит отдает токен авторизации, либо не находит и отдает либо не находит его и дает форбидден

Изначальную таблицу логинов паролей можно накатить через миграции:
Первая миграция создает структуру таблицы
Вторая миграция добавляет тестовые данные

**Comment by BogdanovAleksei** [comment]
В принципе, что бы не плодить дополнительные зависимости в виде контейнеров можно подумать о sqlite, а миграции и дефолтное заполнение можно разделить на 2 скрипта:

**Comment by bobrolov** [comment]
Поправил текст ишака согласно предложению Алексея
