### ISSUE TITLE
Добавить возможность просмотра истории

### ISSUE THREAD

**Issue by bobrolov** [MihailBelyaev/RustTestProject#7]
Добавить в sqlite дополнительную таблицу + миграции, которая хранит историю посещений пользователями разных роутов, ориентируясь по userToken
Таблица вида:
user_id | route | request | timestamp

Сам роут:
GET /history/{id} headers: appToken
response OK + json {
  "id": "String,
  "history":
    [
      {
       "route": "String",
       "request": "String",
       "timestamp": u64
       }
    ]
}
/NotFound/Forbidden

для упрощения можно представить, что ты делаешь бэкенд для какого-то открытого хранилища данных, куда обычные пользователи с логином паролем могут класть свои данные, у тебя это определенная структура, но вообще это могут быть ссылки на картинки, или другой медиаконтент

Так же у этого хранилища есть админка, которая работает по appToken, и админ может добавлять логины пароли, а так же смотреть историю активности пользователей

**Comment by BogdanovAleksei** [comment]
Лучше использовать user_id, так как это более по rest и роут тогда будет `/history/{id}` в базе будет проще искать и варпом удобнее обрабатывать будет! И да, в базе нужна связь между таблицами users и history по полю users - id -> history - user
